version: '2.3'

services:

  frontend:
    build: ./lens-protocol-frontend/.
    ports:
      - 4200:4200
    depends_on:
      - backend

  backend:
    build: ./backend/.
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    hostname: postgres-docker
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nft3_api
    volumes:
        - ./_db/up.sql:/docker-entrypoint-initdb.d/up.sql